// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKP2a5Yp29T6fBPr1DmHFiaThKQqgbj3g',
    appId: '1:82945320504:web:198866b801f3231e34e8cd',
    messagingSenderId: '82945320504',
    projectId: 'twitblind',
    authDomain: 'twitblind.firebaseapp.com',
    storageBucket: 'twitblind.appspot.com',
    measurementId: 'G-FRDJ16G0PP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6-nonthIqqaKeVfJFQw5G5wuhqwcqhC4',
    appId: '1:82945320504:android:1198878ae0b2b57734e8cd',
    messagingSenderId: '82945320504',
    projectId: 'twitblind',
    storageBucket: 'twitblind.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5fK96KOZlVBwLFm5wjEWplpFXITSbsqk',
    appId: '1:82945320504:ios:9fe7089d4694df8534e8cd',
    messagingSenderId: '82945320504',
    projectId: 'twitblind',
    storageBucket: 'twitblind.appspot.com',
    iosClientId: '82945320504-i940ev3cmibcdealeq5f87q8ktutd5dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitblind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5fK96KOZlVBwLFm5wjEWplpFXITSbsqk',
    appId: '1:82945320504:ios:9fe7089d4694df8534e8cd',
    messagingSenderId: '82945320504',
    projectId: 'twitblind',
    storageBucket: 'twitblind.appspot.com',
    iosClientId: '82945320504-i940ev3cmibcdealeq5f87q8ktutd5dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitblind',
  );
}
